//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B403Blog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rol
    {
        public Rol()
        {
            this.KullaniciRols = new HashSet<KullaniciRol>();
        }
    
        public int RolId { get; set; }
        public string RolAdi { get; set; }
    
        public virtual ICollection<KullaniciRol> KullaniciRols { get; set; }
    }
}
